name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: test
      run: python3 -u ./src/test.py -g all > ./etc/out/test.out
    - run: grep -q fail ./etc/out/script.out &&  exit -1 || echo "This job's status is success."
